parameters:

services:
  aws4auth:
    class: PC\Aws4AuthBundle\Listener\RequestListener
    arguments:
      - @request_stack
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onCoreRequest, priority: -1 }
    scope: request