parameters:

services:
  aws4auth:
    class: PC\Aws4AuthBundle\EventListener\RequestListener
    arguments: ["@request_stack", "@annotation_reader"]
    tags:
      - { name: kernel.event_subscriber, event: kernel.request, method: onCoreRequest, priority: -1 }
#    scope: request