<?php

namespace Prime\SecurApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApiKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AwsUserRepository extends EntityRepository
{
}
